### ISSUE TITLE
Use a CDN or storage service for delivering files

### ISSUE THREAD

**Issue by evelynhathaway** [oceanbit-dev/gitshark-website#2]
## To-do

- [x] Proxy all paths to the CDN, default to the `index.html` file if no period in URL (since `try_files` doesn't work when proxying)
- [x] Cache policies for the proxy
- [x] Setup deployment script
- [x] Turn off robots.txt for non-prod
- [x] [Use relative paths using Gatsby for images](https://www.gatsbyjs.com/docs/how-to/images-and-media/importing-assets-into-files/)

## Once Digital Ocean Spaces delivers using HTTP/2

- Add cache policies to CDN sync script
- [Use Gatsby's `--prefix-paths` option for the CI build script](https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/asset-prefix/)
- Confirm that only the index, manifest, and manifest icons are proxied

**Comment by evelynhathaway** [comment]
Closing as it's complete and deployed to production. HTTP/2 + CDN next steps are documented here for the future
